"""Plot only historical CSV files generated by save_historical_csv.py."""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt


def _safe_read_csv(file_path):
	try:
		return pd.read_csv(file_path)
	except Exception as error:
		print(f"Could not read {file_path.name}: {error}")
		return None


def _ensure_date_column(data):
	if "Date" in data.columns:
		return data

	unnamed_first_col = data.columns[0] if len(data.columns) > 0 else None
	if unnamed_first_col and str(unnamed_first_col).startswith("Unnamed"):
		data = data.rename(columns={unnamed_first_col: "Date"})

	return data


def plot_historical_csv(file_path):
	data = _safe_read_csv(file_path)
	if data is None or data.empty:
		return

	data = _ensure_date_column(data)
	if "Date" not in data.columns:
		print(f"{file_path.name} does not have a Date column.")
		return

	data["Date"] = pd.to_datetime(data["Date"], errors="coerce")
	data = data.dropna(subset=["Date"]).sort_values("Date")

	fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
	fig.suptitle(f"Historical - {file_path.stem}", fontsize=12)

	ohlc_columns = ["Open", "High", "Low", "Close"]
	if all(column in data.columns for column in ohlc_columns):
		for column in ohlc_columns:
			line_width = 2 if column == "Close" else 1
			axes[0].plot(data["Date"], data[column], label=column, linewidth=line_width, alpha=0.9)
		axes[0].set_ylabel("Price")
		axes[0].grid(True, alpha=0.3)
		axes[0].legend()
	else:
		axes[0].text(0.5, 0.5, "OHLC columns not found", ha="center", va="center")
		axes[0].set_axis_off()

	if "Volume" in data.columns:
		axes[1].bar(data["Date"], data["Volume"], width=2, alpha=0.6, color="tab:blue")
		axes[1].set_ylabel("Volume")
		axes[1].set_xlabel("Date")
		axes[1].grid(True, alpha=0.3)
	else:
		axes[1].text(0.5, 0.5, "Volume column not found", ha="center", va="center")
		axes[1].set_axis_off()

	fig.tight_layout()


def main():
	data_dir = Path("data")

	if not data_dir.exists():
		print("The data folder does not exist. Run save_historical_csv.py first.")
		return

	historical_files = sorted(data_dir.glob("*_historical_*.csv"))

	if not historical_files:
		print("No historical CSV files found in data. Run save_historical_csv.py to generate them.")
		return

	print("Generating charts for historical CSV files...")
	for file_path in historical_files:
		plot_historical_csv(file_path)

	plt.show()


if __name__ == "__main__":
	main()
